### ISSUE TITLE
sudo-less GPIO access

### ISSUE THREAD

**Issue by sebe** [danrubel/rpi_gpio.dart#10]
Saw this tweet about sudo-less gipo access.
https://twitter.com/ben_nuttall/status/649573697368551425
I did notice the sudo-less GPIO cmd line access in the debian Jessie on my rpi 2,
would be a nice if sudo wasn't required in dart.

**Comment by danrubel** [comment]
Good idea. I'll dig and see what functionality I can provide without sudo.

**Comment by danrubel** [comment]
As part of [overhauling for Dart 2](https://github.com/danrubel/rpi_gpio.dart/issues/12), I'm investigating `/dev/gpiomem` access of GPIO pins which, according to the documentation, can be done when not sudo or root.

**Comment by danrubel** [comment]
New native code in 0.5.0 should allow sudo-less access to gpio pins.
