### ISSUE TITLE
gpio.dispose() causes Crash

### ISSUE THREAD

**Issue by boeledi** [danrubel/rpi_gpio.dart#14]
Hi,

First of all, congratulations for this package.  It really works very well.

There is only one problem with the gpio.dispose() method which generates a CRASH report.

Here is the error:
`
===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x76f63034
version=2.3.1 (Tue May 21 19:28:38 2019 +0200) on "linux_arm"
thread=1753, isolate=main(0x2392600)
  pc 0x76f0fa14 fp 0x7063e1ec readGpio(_Dart_NativeArguments*)
-- End of DumpStackTrace
Aborted
`
I am running Dart:  Dart VM version: 2.3.1 (Tue May 21 19:28:38 2019 +0200) on "linux_arm"

Many thanks in advance for your help.

**Comment by danrubel** [comment]
This package has been updated to use `dart:ffi` and now runs on Dart SDK 2.18.
Please re-open if this problem still occurs with the latest `rpi_gpio` code.
