### ISSUE TITLE
Use `dart:ffi` for native code?

### ISSUE THREAD

**Issue by simolus3** [danrubel/rpi_gpio.dart#21]
Thanks for your awesome work on this package.

This package uses `dart-ext` imports to access native code, a mechanism that is deprecated and will be removed in Dart 2.15. I wonder if you have considered using `dart:ffi` to bind to native code instead?
I'm happy to send in a PR if you're interested.

**Comment by danrubel** [comment]
I have not had time to look into `dart:ffi`, but I definitely want to move in that direction.
It would be wonderful if you have the time to pull together a PR.
No worries if you are busy... I will get to it when I can.

**Comment by simolus3** [comment]
I broke my PI out of stupidity (short-circuited the wrong pins) so it looks like I won't be finishing a PR for this soon :( Sorry for over-promising!

**Comment by danrubel** [comment]
No worries!
I'll get to it when I can.

**Comment by danrubel** [comment]
This package has been updated to use `dart:ffi` and now runs on Dart SDK 2.18
